//
//  GameScene.h
//  practice
//

//  Copyright (c) 2014 Fluxfire. All rights reserved.
//

#import <SpriteKit/SpriteKit.h>
#import <AVFoundation/AVFoundation.h>

@import SpriteKit;


@class NormalLogic;
@class MainMenu;
@class ArcadeMenu;
@class Food;
@class FBLabelLogic;
@class RankLogic;
@class ShopLogic;
@class PowerUpLogic;

BOOL beatObj;
BOOL stop;
BOOL fix;
BOOL newGame;
BOOL canSwipe;
BOOL canBlock;
BOOL canEat;
BOOL canTaunt;
BOOL resumeFromLoss;
BOOL freeze;
BOOL goDelay;
BOOL pay;
BOOL pay500;
BOOL pay750;
BOOL pay1000;
BOOL pay1250;
BOOL pay2000;
BOOL pay3000;
BOOL pay4000;
BOOL pay5000;
BOOL pay6000;
BOOL pay7000;
BOOL pay8000;
BOOL pay9000;
BOOL invalidateTimer;
BOOL canHelp;
BOOL foodBlowReggy;
BOOL canBat;
BOOL noFreeze;
BOOL threeXDam;
BOOL critHit;
int tauntInt;



@interface GameScene : SKScene <SKPhysicsContactDelegate, AVAudioPlayerDelegate> {
    
    //Game Sprites
    SKTexture *backgroundTexture;
    SKSpriteNode *background;
    SKTexture *leftSensorTexture;
    SKSpriteNode *leftSensor;
    SKTexture *rightSensorTexture;
    SKSpriteNode *rightSensor;
    SKTexture *bottomSensorTexture;
    SKSpriteNode *bottomSensor;
    SKTexture *spriteTexture;
    SKSpriteNode *sprite;
    SKTexture *fakeSpriteTexture;
    SKSpriteNode *fakeSprite;
    
    //CountDown Sprites
    SKTexture *startGameTexture;
    SKSpriteNode *startGame;
    SKTexture *threeTexture;
    SKSpriteNode *three;
    SKTexture *twoTexture;
    SKSpriteNode *two;
    SKTexture *oneTexture;
    SKSpriteNode *one;
    SKTexture *tutorialTexture;
    SKSpriteNode *tutorial;
    //Machine Sprites
    SKTexture *foodDropperTexture;
    SKSpriteNode *foodDropper;
    SKTexture *foodCatcherTexture;
    SKSpriteNode *foodCatcher;
    SKTexture *foodCatcherHoleTexture;
    SKSpriteNode *foodCatcherHole;
    //Game Over Sprites
    SKTexture *scoreBoardTexture;
    SKSpriteNode *scoreBoard;
    SKTexture *blackScreenTexture;
    SKSpriteNode *blackScreen;
    SKTexture *backButtonTexture;
    SKSpriteNode *backButton;
    SKTexture *gameOverTextTexture;
    SKSpriteNode *gameOverText;
    SKTexture *homeButtonTexture;
    SKSpriteNode *homeButton;
    SKTexture *replayButtonTexture;
    SKSpriteNode *replayButton;
    SKTexture *dunceIconTexture;
    SKSpriteNode *dunceIcon;
    SKTexture *bozoIconTexture;
    SKSpriteNode *bozoIcon;
    SKTexture *boneHeadIconTexture;
    SKSpriteNode *boneHeadIcon;
    SKTexture *dingusIconTexture;
    SKSpriteNode *dingusIcon;
    NSString *saveString;
    NSSet *foodCheck;
    //Backgound Animation Sprites
    SKTexture *inGameBG1Texture;
    SKSpriteNode *inGameBG1;
    //PowerUp Animation Sprites
    SKTexture *l1H1Texture;
    SKSpriteNode *l1H1;
    SKTexture *l1H2Texture;
    SKSpriteNode *l1H2;
    SKTexture *l1H3Texture;
    SKSpriteNode *l1H3;
    SKTexture *l1H4Texture;
    SKSpriteNode *l1H4;
    SKTexture *l1H5Texture;
    SKSpriteNode *l1H5;
    SKTexture *l1H6Texture;
    SKSpriteNode *l1H6;
    SKTexture *l1H7Texture;
    SKSpriteNode *l1H7;
    SKTexture *l2H1Texture;
    SKSpriteNode *l2H1;
    SKTexture *l2H2Texture;
    SKSpriteNode *l2H2;
    SKTexture *l2H3Texture;
    SKSpriteNode *l2H3;
    SKTexture *l2H4Texture;
    SKSpriteNode *l2H4;
    SKTexture *l2H5Texture;
    SKSpriteNode *l2H5;
    SKTexture *l2H6Texture;
    SKSpriteNode *l2H6;
    SKTexture *l2H7Texture;
    SKSpriteNode *l2H7;
    SKTexture *l3H1Texture;
    SKSpriteNode *l3H1;
    SKTexture *l3H2Texture;
    SKSpriteNode *l3H2;
    SKTexture *l3H3Texture;
    SKSpriteNode *l3H3;
    SKTexture *l3H4Texture;
    SKSpriteNode *l3H4;
    SKTexture *l3H5Texture;
    SKSpriteNode *l3H5;
    SKTexture *l3H6Texture;
    SKSpriteNode *l3H6;
    SKTexture *l3H7Texture;
    SKSpriteNode *l3H7;
    SKTexture *doublePointsSymbolTexture;
    SKSpriteNode *doublePointsSymbol;
    SKTexture *triplePointsSymbolTexture;
    SKSpriteNode *triplePointsSymbol;
    SKTexture *quadPointsSymbolTexture;
    SKSpriteNode *quadPointsSymbol;
    SKTexture *hG10P0Texture;
    SKSpriteNode *hG10P0;
    SKTexture *hG10P1Texture;
    SKSpriteNode *hG10P1;
    SKTexture *hG10P2Texture;
    SKSpriteNode *hG10P2;
    SKTexture *hG10P3Texture;
    SKSpriteNode *hG10P3;
    SKTexture *hG10P4Texture;
    SKSpriteNode *hG10P4;
    SKTexture *hG10P5Texture;
    SKSpriteNode *hG10P5;
    SKTexture *hG20P0Texture;
    SKSpriteNode *hG20P0;
    SKTexture *hG20P1Texture;
    SKSpriteNode *hG20P1;
    SKTexture *hG20P2Texture;
    SKSpriteNode *hG20P2;
    SKTexture *hG20P3Texture;
    SKSpriteNode *hG20P3;
    SKTexture *hG20P4Texture;
    SKSpriteNode *hG20P4;
    SKTexture *hG20P5Texture;
    SKSpriteNode *hG20P5;
    SKTexture *hG30P0Texture;
    SKSpriteNode *hG30P0;
    SKTexture *hG30P1Texture;
    SKSpriteNode *hG30P1;
    SKTexture *hG30P2Texture;
    SKSpriteNode *hG30P2;
    SKTexture *hG30P3Texture;
    SKSpriteNode *hG30P3;
    SKTexture *hG30P4Texture;
    SKSpriteNode *hG30P4;
    SKTexture *hG30P5Texture;
    SKSpriteNode *hG30P5;
    SKTexture *tr10Texture;
    SKSpriteNode *tr10;
    SKTexture *tr20Texture;
    SKSpriteNode *tr20;
    SKTexture *tr30Texture;
    SKSpriteNode *tr30;
    //PowerUp Holder Sprites
    SKTexture *doublePointsPHTexture;
    SKSpriteNode *doublePointsPH;
    SKTexture *extraLife1PHTexture;
    SKSpriteNode *extraLife1PH;
    SKTexture *extraLife2PHTexture;
    SKSpriteNode *extraLife2PH;
    SKTexture *extraLife3PHTexture;
    SKSpriteNode *extraLife3PH;
    SKTexture *headStart10PHTexture;
    SKSpriteNode *headStart10PH;
    SKTexture *headStart20PHTexture;
    SKSpriteNode *headStart20PH;
    SKTexture *headStart30PHTexture;
    SKSpriteNode *headStart30PH;
    SKTexture *hourGlass10PHTexture;
    SKSpriteNode *hourGlass10PH;
    SKTexture *hourGlass20PHTexture;
    SKSpriteNode *hourGlass20PH;
    SKTexture *hourGlass30PHTexture;
    SKSpriteNode *hourGlass30PH;
    SKTexture *doublePointsSPTexture;
    SKSpriteNode *doublePointsSP;
    SKTexture *triplePointsSPTexture;
    SKSpriteNode *triplePointsSP;
    SKTexture *quadPointsSPTexture;
    SKSpriteNode *quadPointsSP;
    SKTexture *extraLife1SPTexture;
    SKSpriteNode *extraLife1SP;
    SKTexture *extraLife2SPTexture;
    SKSpriteNode *extraLife2SP;
    SKTexture *extraLife3SPTexture;
    SKSpriteNode *extraLife3SP;
    SKTexture *headStart10SPTexture;
    SKSpriteNode *headStart10SP;
    SKTexture *headStart20SPTexture;
    SKSpriteNode *headStart20SP;
    SKTexture *headStart30SPTexture;
    SKSpriteNode *headStart30SP;
    SKTexture *hourGlass10SPTexture;
    SKSpriteNode *hourGlass10SP;
    SKTexture *hourGlass20SPTexture;
    SKSpriteNode *hourGlass20SP;
    SKTexture *hourGlass30SPTexture;
    SKSpriteNode *hourGlass30SP;
    SKTexture *powerUpHolderTexture;
    SKSpriteNode *powerUpHolder;
    SKTexture *quadPointsPHTexture;
    SKSpriteNode *quadPointsPH;
    SKTexture *tier1ButtonTexture;
    SKSpriteNode *tier1Button;
    SKTexture *tier2ButtonTexture;
    SKSpriteNode *tier2Button;
    SKTexture *tier3ButtonTexture;
    SKSpriteNode *tier3Button;
    SKTexture *triplePointsPHTexture;
    SKSpriteNode *triplePointsPH;
    SKTexture *tier1PowerUpsTexture;
    SKSpriteNode *tier1PowerUps;
    SKTexture *tier2PowerUpsTexture;
    SKSpriteNode *tier2PowerUps;
    SKTexture *tier3PowerUpsTexture;
    SKSpriteNode *tier3PowerUps;
    
    //PauseMenu Sprites
    SKTexture *factoryBucksTitleBoxTexture;
    SKSpriteNode *factoryBucksTitleBox;
    SKTexture *buy300kTexture;
    SKSpriteNode *buy300k;
    SKTexture *buy150kTexture;
    SKSpriteNode *buy150k;
    SKTexture *buy75kTexture;
    SKSpriteNode *buy75k;
    SKTexture *buy45kTexture;
    SKSpriteNode *buy45k;
    SKTexture *buy30kTexture;
    SKSpriteNode *buy30k;
    SKTexture *buy9kTexture;
    SKSpriteNode *buy9k;
    SKTexture *gSBlackScreenTexture;
    SKSpriteNode *gSBlackScreen;
    SKTexture *gSHomeTexture;
    SKSpriteNode *gSHome;
    SKTexture *gSRestartTexture;
    SKSpriteNode *gSRestart;
    SKTexture *maxUpgradeBoxesTexture;
    SKSpriteNode *maxUpgradeBoxes;
    SKTexture *okTexture;
    SKSpriteNode *ok;
    SKTexture *pauseTexture;
    SKSpriteNode *pause;
    SKTexture *pMBoxesTexture;
    SKSpriteNode *pMBoxes;
    SKTexture *pMBuyTexture;
    SKSpriteNode *pMBuy;
    SKTexture *pMBuy1Texture;
    SKSpriteNode *pMBuy1;
    SKTexture *pMFactoryBucksButtonTexture;
    SKSpriteNode *pMFactoryBucksButton;
    SKTexture *pMPowerUpsButtonTexture;
    SKSpriteNode *pMPowerUpsButton;
    SKTexture *powerUpsTitleBoxTexture;
    SKSpriteNode *powerUpsTitleBox;
    SKTexture *resumeTexture;
    SKSpriteNode *resume;
    SKTexture *retryBoxTexture;
    SKSpriteNode *retryBox;
    SKTexture *retryBox2Texture;
    SKSpriteNode *retryBox2;
    SKTexture *box991Texture;
    SKSpriteNode *box991;
    SKTexture *box992Texture;
    SKSpriteNode *box992;
    SKTexture *waitBoxTexture;
    SKSpriteNode *waitBox;
    SKTexture *timeCircleTexture;
    SKSpriteNode *timeCircle;
    SKTexture *uPGTexture;
    SKSpriteNode *uPG;
    SKTexture *uPG1Texture;
    SKSpriteNode *uPG1;
    SKTexture *upgradeTexture;
    SKSpriteNode *upgrade;
    SKTexture *pdSceneTexture;
    SKSpriteNode *pdScene;
    SKTexture *pmSceneTexture;
    SKSpriteNode *pmScene;
    SKTexture *srSceneTexture;
    SKSpriteNode *srScene;
    SKTexture *elSceneTexture;
    SKSpriteNode *elScene;
    SKTexture *trSceneTexture;
    SKSpriteNode *trScene;
    SKTexture *puBuy1Texture;
    SKSpriteNode *puBuy1;
    SKTexture *puBuy2Texture;
    SKSpriteNode *puBuy2;
    SKTexture *puBuy3Texture;
    SKSpriteNode *puBuy3;
    SKTexture *puBuy4Texture;
    SKSpriteNode *puBuy4;
    SKTexture *puBuy5Texture;
    SKSpriteNode *puBuy5;
    SKTexture *puBuy6Texture;
    SKSpriteNode *puBuy6;
    SKTexture *puBuy7Texture;
    SKSpriteNode *puBuy7;
    SKTexture *puBuy8Texture;
    SKSpriteNode *puBuy8;
    SKTexture *puBuy9Texture;
    SKSpriteNode *puBuy9;
    SKTexture *puBuy10Texture;
    SKSpriteNode *puBuy10;
    SKTexture *puBuy11Texture;
    SKSpriteNode *puBuy11;
    SKTexture *puBuy12Texture;
    SKSpriteNode *puBuy12;
    
    //Sounds
    AVAudioPlayer *Woosh;
    
    //VictorySprites
    SKTexture *blueMarlinIconTexture;
    SKSpriteNode *blueMarlinIcon;
    SKTexture *blueTangIconTexture;
    SKSpriteNode *blueTangIcon;
    SKTexture *dolphinIconTexture;
    SKSpriteNode *dolphinIcon;
    SKTexture *silverCrownTexture;
    SKSpriteNode *silverCrown;
    SKTexture *bronzeCrownTexture;
    SKSpriteNode *bronzeCrown;
    SKTexture *goldCrownTexture;
    SKSpriteNode *goldCrown;
    SKTexture *hermitCrabIconTexture;
    SKSpriteNode *hermitCrabIcon;
    SKTexture *killerWhaleIconTexture;
    SKSpriteNode *killerWhaleIcon;
    SKTexture *lBlueMarlinIconTexture;
    SKSpriteNode *lBlueMarlinIcon;
    SKTexture *lBlueTangIconTexture;
    SKSpriteNode *lBlueTangIcon;
    SKTexture *lDolphinIconTexture;
    SKSpriteNode *lDolphinIcon;
    SKTexture *lHermitCrabIconTexture;
    SKSpriteNode *lHermitCrabIcon;
    SKTexture *lKillerWhaleIconTexture;
    SKSpriteNode *lKillerWhaleIcon;
    SKTexture *lOctopusIconTexture;
    SKSpriteNode *lOctopusIcon;
    SKTexture *lSealIconTexture;
    SKSpriteNode *lSealIcon;
    SKTexture *lSharkIconTexture;
    SKSpriteNode *lSharkIcon;
    SKTexture *lShrimpIconTexture;
    SKSpriteNode *lShrimpIcon;
    SKTexture *lWhaleIconTexture;
    SKSpriteNode *lWhaleIcon;
    SKTexture *nextButtonTexture;
    SKSpriteNode *nextButton;
    SKTexture *octopusIconTexture;
    SKSpriteNode *octopusIcon;
    SKTexture *rBlueMarlinIconTexture;
    SKSpriteNode *rBlueMarlinIcon;
    SKTexture *rBlueTangIconTexture;
    SKSpriteNode *rBlueTangIcon;
    SKTexture *rDolphinIconTexture;
    SKSpriteNode *rDolphinIcon;
    SKTexture *rHermitCrabIconTexture;
    SKSpriteNode *rHermitCrabIcon;
    SKTexture *rKillerWhaleIconTexture;
    SKSpriteNode *rKillerWhaleIcon;
    SKTexture *rOctopusIconTexture;
    SKSpriteNode *rOctopusIcon;
    SKTexture *rSealIconTexture;
    SKSpriteNode *rSealIcon;
    SKTexture *rSharkIconTexture;
    SKSpriteNode *rSharkIcon;
    SKTexture *rShrimpIconTexture;
    SKSpriteNode *rShrimpIcon;
    SKTexture *rWhaleIconTexture;
    SKSpriteNode *rWhaleIcon;
    SKTexture *sealIconTexture;
    SKSpriteNode *sealIcon;
    SKTexture *sharkIconTexture;
    SKSpriteNode *sharkIcon;
    SKTexture *shrimpIconTexture;
    SKSpriteNode *shrimpIcon;
    SKTexture *whaleIconTexture;
    SKSpriteNode *whaleIcon;
    SKTexture *smokeTexture;
    SKSpriteNode *smoke;
    SKTexture *reggyFaceTexture;
    SKSpriteNode *reggyFace;
    AVAudioPlayer *phrase;
    
    //GOPUH
    SKTexture *gOPUHTexture;
    SKSpriteNode *gOPUH;
    SKTexture *gOPUHNumsTexture;
    SKSpriteNode *gOPUHNums;
    SKTexture *gOPUHBuyTexture;
    SKSpriteNode *gOPUHBuy;
    SKTexture *gOPUHBuy1Texture;
    SKSpriteNode *gOPUHBuy1;
    SKTexture *gOPUHBuy2Texture;
    SKSpriteNode *gOPUHBuy2;
    SKTexture *gOPUHBuy3Texture;
    SKSpriteNode *gOPUHBuy3;
    
    //Pause Menu
    SKTexture *mTUBP5Texture;
    SKSpriteNode *mTUBP5;
    SKTexture *mPPG1Texture;
    SKSpriteNode *mPPG1;
    SKTexture *pM1ExtraLifeTextTexture;
    SKSpriteNode *pM1ExtraLifeText;
    SKTexture *pM2ExtraLivesTextTexture;
    SKSpriteNode *pM2ExtraLivesText;
    SKTexture *pM3ExtraLivesTextTexture;
    SKSpriteNode *pM3ExtraLivesText;
    SKTexture *pM3KFactoryBucksTextTexture;
    SKSpriteNode *pM3KFactoryBucksText;
    SKTexture *pM5KTextTexture;//
    SKSpriteNode *pM5KText;
    SKTexture *pM6KFactoryBucksTextTexture;
    SKSpriteNode *pM6KFactoryBucksText;
    SKTexture *pM9KFactoryBucksTextTexture;//
    SKSpriteNode *pM9KFactoryBucksText;
    SKTexture *pM10KFactoryBucksTextTexture;//
    SKSpriteNode *pM10KFactoryBucksText;
    SKTexture *pM10kTextTexture;
    SKSpriteNode *pM10kText;
    SKTexture *pM20KFactoryBucksTextTexture;
    SKSpriteNode *pM20KFactoryBucksText;
    SKTexture *pM27kTextTexture;
    SKSpriteNode *pM27kText;
    SKTexture *pM45kTextTexture;
    SKSpriteNode *pM45kText;
    SKTexture *pM72kTextTexture;
    SKSpriteNode *pM72kText;
    SKTexture *PM99Texture;
    SKSpriteNode *PM99;
    SKTexture *pM099Texture;
    SKSpriteNode *pM099;
    SKTexture *pM299Texture;
    SKSpriteNode *pM299;
    SKTexture *pM1999Texture;
    SKSpriteNode *pM1999;
    SKTexture *pM4999Texture;
    SKSpriteNode *pM4999;
    SKTexture *pM9999Texture;
    SKSpriteNode *pM9999;
    SKTexture *pMB1ExtraLifeTexture;
    SKSpriteNode *pMB1ExtraLife;
    SKTexture *pMB2ExtraLivesTexture;
    SKSpriteNode *pMB2ExtraLives;
    SKTexture *pMB3ExtraLivessTexture;
    SKSpriteNode *pMB3ExtraLivess;
    SKTexture *pMB5kTexture;
    SKSpriteNode *pMB5k;
    SKTexture *pMB10kTexture;
    SKSpriteNode *pMB10k;
    SKTexture *pMB27kTexture;
    SKSpriteNode *pMB27k;
    SKTexture *pMB45kTexture;
    SKSpriteNode *pMB45k;
    SKTexture *pMB72kTexture;
    SKSpriteNode *pMB72k;
    SKTexture *pMB144kTexture;
    SKSpriteNode *pMB144k;
    SKTexture *pMBDoublePointsTexture;
    SKSpriteNode *pMBDoublePoints;
    SKTexture *pMBHeadStart10Texture;
    SKSpriteNode *pMBHeadStart10;
    SKTexture *pMBHeadStart20Texture;
    SKSpriteNode *pMBHeadStart20;
    SKTexture *pMBHeadStart30Texture;
    SKSpriteNode *pMBHeadStart30;
    SKTexture *pMBQuadPointsTexture;
    SKSpriteNode *pMBQuadPoints;
    SKTexture *pMBSpeedReducer10Texture;
    SKSpriteNode *pMBSpeedReducer10;
    SKTexture *pMBSpeedReducer20Texture;
    SKSpriteNode *pMBSpeedReducer20;
    SKTexture *pMBSpeedReducer30Texture;
    SKSpriteNode *pMBSpeedReducer30;
    SKTexture *pMBTriplePointsTexture;
    SKSpriteNode *pMBTriplePoints;
    SKTexture *pMDoublePointsTextTexture;
    SKSpriteNode *pMDoublePointsText;
    SKTexture *pMHeadStart10TextTexture;
    SKSpriteNode *pMHeadStart10Text;
    SKTexture *pMHeadStart20TextTexture;
    SKSpriteNode *pMHeadStart20Text;
    SKTexture *pMHeadStart30TextTexture;
    SKSpriteNode *pMHeadStart30Text;
    SKTexture *pMPowerUpAmountLabelTexture;
    SKSpriteNode *pMPowerUpAmountLabel;
    SKTexture *pMQuadPointTextTexture;
    SKSpriteNode *pMQuadPointText;
    SKTexture *pMS1ExtraLifeTexture;
    SKSpriteNode *pMS1ExtraLife;
    SKTexture *pMS2ExtraLivesTexture;
    SKSpriteNode *pMS2ExtraLives;
    SKTexture *pMS3ExtralLivesTexture;
    SKSpriteNode *pMS3ExtralLives;
    SKTexture *pMSDoublePointsTexture;
    SKSpriteNode *pMSDoublePoints;
    SKTexture *pMSHeadStart10Texture;
    SKSpriteNode *pMSHeadStart10;
    SKTexture *pMSHeadStart20Texture;
    SKSpriteNode *pMSHeadStart20;
    SKTexture *pMSHeadStart30Texture;
    SKSpriteNode *pMSHeadStart30;
    SKTexture *pMSpeedReducer10TextTexture;
    SKSpriteNode *pMSpeedReducer10Text;
    SKTexture *pMSpeedReducer20TextTexture;//
    SKSpriteNode *pMSpeedReducer20Text;
    SKTexture *pMSpeedReducer30TextTexture;//
    SKSpriteNode *pMSpeedReducer30Text;
    SKTexture *pMSQuadPointsTexture;//
    SKSpriteNode *pMSQuadPoints;
    SKTexture *pMSSpeedReducer10Texture;
    SKSpriteNode *pMSSpeedReducer10;
    SKTexture *pMSSpeedReducer20Texture;
    SKSpriteNode *pMSSpeedReducer20;
    SKTexture *pMSSpeedReducer30Texture;
    SKSpriteNode *pMSSpeedReducer30;
    SKTexture *pMSTriplePointsTexture;
    SKSpriteNode *pMSTriplePoints;
    SKTexture *pMTDoublePointsTexture;
    SKSpriteNode *pMTDoublePoints;
    SKTexture *pMTop10kTexture;
    SKSpriteNode *pMTop10k;
    SKTexture *pMTop27KTexture;
    SKSpriteNode *pMTop27K;
    SKTexture *pMTop45kTexture;
    SKSpriteNode *pMTop45k;
    SKTexture *pMTop72kTexture;
    SKSpriteNode *pMTop72k;
    SKTexture *pMTop144kTexture;
    SKSpriteNode *pMTop144k;
    SKTexture *pMTopCommingSoonTexture;
    SKSpriteNode *pMTopCommingSoon;
    SKTexture *pMTopExtraLivesTexture;
    SKSpriteNode *pMTopExtraLives;
    SKTexture *pMTopHeadStartTexture;
    SKSpriteNode *pMTopHeadStart;
    SKTexture *pMTopSpeedReducerTexture;
    SKSpriteNode *pMTopSpeedReducer;
    SKTexture *pMTriplePointsTextTexture;
    SKSpriteNode *pMTriplePointsText;
    
    SKTexture *maxBorderTexture;
    SKSpriteNode *maxBorder;
    SKTexture *robotHeadTexture;
    SKSpriteNode *robotHead;
    
    SKTexture *bronzeAcornTexture;
    SKSpriteNode *bronzeAcorn;
    SKTexture *bronzeAppleTexture;
    SKSpriteNode *bronzeApple;
    SKTexture *bronzeBarTexture;
    SKSpriteNode *bronzeBar;
    SKTexture *bronzeChaliceTexture;
    SKSpriteNode *bronzeChalice;
    SKTexture *bronzeEagleTexture;
    SKSpriteNode *bronzeEagle;
    SKTexture *bronzeGolfClubTexture;
    SKSpriteNode *bronzeGolfClub;
    SKTexture *bronzeMicrophoneTexture;
    SKSpriteNode *bronzeMicrophone;
    SKTexture *bronzeSwordsTexture;
    SKSpriteNode *bronzeSwords;
    SKTexture *bronzeUnicronTexture;
    SKSpriteNode *bronzeUnicron;
    SKTexture *bronzeWatchTexture;
    SKSpriteNode *bronzeWatch;
    
    SKTexture *silverAcornTexture;
    SKSpriteNode *silverAcorn;
    SKTexture *silverAppleTexture;
    SKSpriteNode *silverApple;
    SKTexture *silverBarTexture;
    SKSpriteNode *silverBar;
    SKTexture *silverChaliceTexture;
    SKSpriteNode *silverChalice;
    SKTexture *silverEagleTexture;
    SKSpriteNode *silverEagle;
    SKTexture *silverGolfClubTexture;
    SKSpriteNode *silverGolfClub;
    SKTexture *silverMicrophoneTexture;
    SKSpriteNode *silverMicrophone;
    SKTexture *silverSwordsTexture;
    SKSpriteNode *silverSwords;
    SKTexture *silverUnicronTexture;
    SKSpriteNode *silverUnicron;
    SKTexture *silverWatchTexture;
    SKSpriteNode *silverWatch;
    
    SKTexture *goldenAcornTexture;
    SKSpriteNode *goldenAcorn;
    SKTexture *goldenAppleTexture;
    SKSpriteNode *goldenApple;
    SKTexture *goldenBarTexture;
    SKSpriteNode *goldenBar;
    SKTexture *goldenChaliceTexture;
    SKSpriteNode *goldenChalice;
    SKTexture *goldenEagleTexture;
    SKSpriteNode *goldenEagle;
    SKTexture *goldenGolfClubTexture;
    SKSpriteNode *goldenGolfClub;
    SKTexture *goldenMicrophoneTexture;
    SKSpriteNode *goldenMicrophone;
    SKTexture *goldenSwordsTexture;
    SKSpriteNode *goldenSwords;
    SKTexture *goldenUnicronTexture;
    SKSpriteNode *goldenUnicron;
    SKTexture *goldenWatchTexture;
    SKSpriteNode *goldenWatch;
    
    SKTexture *sidePUHolderPMTexture;
    SKSpriteNode *sidePUHolderPM;
    SKTexture *fBLabelPMTexture;
    SKSpriteNode *fBLabelPM;
    SKTexture *speedReducerPMTexture;
    SKSpriteNode *speedReducerPM;
    SKTexture *headStartPMTexture;
    SKSpriteNode *headStartPM;
    SKTexture *extraLivesPMTexture;
    SKSpriteNode *extraLivesPM;
    SKTexture *sidePMTexture;
    SKSpriteNode *sidePM;
    SKTexture *sidePDTexture;
    SKSpriteNode *sidePD;
    SKTexture *sideSRTexture;
    SKSpriteNode *sideSR;
    SKTexture *sideELTexture;
    SKSpriteNode *sideEL;
    SKTexture *sideHSTexture;
    SKSpriteNode *sideHS;
    SKTexture *sideCSTexture;
    SKSpriteNode *sideCS;
    SKTexture *crownBlingTexture;
    SKSpriteNode *crownBling;
    
    SKTexture *life1MachineTexture;
    SKSpriteNode *life1Machine;
    SKTexture *life1MachineBackgroundTexture;
    SKSpriteNode *life1MachineBackground;
    SKTexture *life2MachineTexture;
    SKSpriteNode *life2Machine;
    SKTexture *life2MachineBackgroundTexture;
    SKSpriteNode *life2MachineBackground;
    SKTexture *life3MachineTexture;
    SKSpriteNode *life3Machine;
    SKTexture *life3MachineBackgroundTexture;
    SKSpriteNode *life3MachineBackground;
    SKTexture *life4MachineTexture;
    SKSpriteNode *life4Machine;
    SKTexture *life4MachineBackgroundTexture;
    SKSpriteNode *life4MachineBackground;
    SKTexture *life5MachineTexture;
    SKSpriteNode *life5Machine;
    SKTexture *life5MachineBackgroundTexture;
    SKSpriteNode *life5MachineBackground;
    SKTexture *life6MachineTexture;
    SKSpriteNode *life6Machine;
    SKTexture *life6MachineBackgroundTexture;
    SKSpriteNode *life6MachineBackground;
    SKTexture *life7MachineTexture;
    SKSpriteNode *life7Machine;
    SKTexture *life7MachineBackgroundTexture;
    SKSpriteNode *life7MachineBackground;
    SKTexture *life8MachineTexture;
    SKSpriteNode *life8Machine;
    SKTexture *life8MachineBackgroundTexture;
    SKSpriteNode *life8MachineBackground;
    SKTexture *life9MachineTexture;
    SKSpriteNode *life9Machine;
    SKTexture *life9MachineBackgroundTexture;
    SKSpriteNode *life9MachineBackground;
    SKTexture *life10MachineTexture;
    SKSpriteNode *life10Machine;
    SKTexture *life10MachineBackgroundTexture;
    SKSpriteNode *life10MachineBackground;
    SKTexture *lifeMachineLocksTexture;
    SKSpriteNode *lifeMachineLocks;
    SKTexture *lifeMachineUPGButtonTexture;
    SKSpriteNode *lifeMachineUPGButton;
    
    SKTexture *texture;
    SKTexture *foodDFood;
    SKTexture *iWonderMouthsTexture;
    SKSpriteNode *iWonderMouths;
    SKTexture *yourMadMouthsTexture;
    SKSpriteNode *yourMadMouths;
    SKTexture *foodDFoodSKTexture;
    SKSpriteNode *foodDFoodSK;
    SKTexture *sideFoodTexture;
    SKSpriteNode *sideFood;
    SKTexture *backgroundAnimTexture;
    SKSpriteNode *backgroundAnim;
    NSTimer *timer;
    NSTimer *timer05;
    NSTimer *timer15;
    NSTimer *timer2;
    AVAudioPlayer *iWonderSound;
    AVAudioPlayer *youMadSound;
    AVAudioPlayer *lightning;
    SKTexture *robotEyesTexture;
    SKSpriteNode *robotEyes;
    SKTexture *robotEyeBrowsTexture;
    SKSpriteNode *robotEyeBrows;
    SKTexture *timerMachineTexture;
    SKSpriteNode *timerMachine;
    SKTexture *amountMachineTexture;
    SKSpriteNode *amountMachine;
    SKTexture *amountMachineLight1Texture;
    SKSpriteNode *amountMachineLight1;
    SKTexture *amountMachineLight2Texture;
    SKSpriteNode *amountMachineLight2;
    AVAudioPlayer *zoop;
    AVAudioPlayer *buzzer;
    AVAudioPlayer *brokenGlass;
    AVAudioPlayer *ching;
    SKTexture *el1GlassTexture;
    SKSpriteNode *el1Glass;
    SKTexture *el2GlassTexture;
    SKSpriteNode *el2Glass;
    SKTexture *el3GlassTexture;
    SKSpriteNode *el3Glass;
    
    SKTexture *ReggyBotTexture;
    SKSpriteNode *ReggyBot;
    SKTexture *ReggySheildTexture;
    SKSpriteNode *ReggySheild;
    SKTexture *ReggyFlashTexture;
    SKSpriteNode *ReggyFlash;
    SKTexture *foodBlowerTexture;
    SKSpriteNode *foodBlower;
    SKTexture *curtainTexture;
    SKSpriteNode *curtain;
    SKTexture *rockTexture;
    SKSpriteNode *rock;
    SKTexture *crackedScreenTexture;
    SKSpriteNode *crackedScreen;
    SKTexture *eggTexture;
    SKSpriteNode *egg;
    SKTexture *eggedScreenTexture;
    SKSpriteNode *eggedScreen;
    SKTexture *lightningShadowTexture;
    SKSpriteNode *lightningShadow;
    SKTexture *rubbleTexture;
    SKSpriteNode *rubble;
    SKTexture *healthBarIconTexture;
    SKSpriteNode *healthBarIcon;
    SKTexture *energyBarTexture;
    SKSpriteNode *energyBar;
    SKTexture *healthBarTexture;
    SKSpriteNode *healthBar;
    SKTexture *humanHealthBarIconTexture;
    SKSpriteNode *humanHealthBarIcon;
    SKTexture *humanHealthBarMachineTexture;
    SKSpriteNode *humanHealthBarMachine;
    SKTexture *humanEnergyBarTexture;
    SKSpriteNode *humanEnergyBar;
    SKTexture *humanHealthBarTexture;
    SKSpriteNode *humanHealthBar;
    SKSpriteNode *foodBlowSensor;
    AVAudioPlayer *deadBatteries;
    AVAudioPlayer *TauntA;
    AVAudioPlayer *TauntAa;
    AVAudioPlayer *TauntB;
    AVAudioPlayer *TauntBb;
    AVAudioPlayer *TauntC;
    AVAudioPlayer *TauntCc;
    AVAudioPlayer *TauntD;
    AVAudioPlayer *TauntDd;
    AVAudioPlayer *TauntE;
    AVAudioPlayer *TauntEe;
    AVAudioPlayer *TauntF;
    AVAudioPlayer *TauntFf;
    AVAudioPlayer *TauntG;
    AVAudioPlayer *TauntGg;
    AVAudioPlayer *TauntH;
    AVAudioPlayer *TauntHh;
    AVAudioPlayer *TauntI;
    AVAudioPlayer *TauntIi;
    AVAudioPlayer *TauntJ;
    AVAudioPlayer *TauntJj;
    AVAudioPlayer *TauntK;
    AVAudioPlayer *TauntKk;
    AVAudioPlayer *TauntL;
    AVAudioPlayer *TauntLl;
    AVAudioPlayer *TauntM;
    AVAudioPlayer *TauntMm;
    AVAudioPlayer *TauntN;
    AVAudioPlayer *TauntNn;
    AVAudioPlayer *TauntO;
    AVAudioPlayer *TauntOo;
    AVAudioPlayer *TauntP;
    AVAudioPlayer *TauntPp;
    AVAudioPlayer *TauntQ;
    AVAudioPlayer *TauntQq;
    AVAudioPlayer *TauntR;
    AVAudioPlayer *TauntRr;
    AVAudioPlayer *TauntS;
    AVAudioPlayer *TauntSs;
    AVAudioPlayer *TauntT;
    AVAudioPlayer *TauntTt;
    AVAudioPlayer *TauntU;
    AVAudioPlayer *TauntUu;
    AVAudioPlayer *TauntV;
    AVAudioPlayer *TauntVv;
    AVAudioPlayer *TauntW;
    AVAudioPlayer *TauntWw;
    AVAudioPlayer *TauntX;
    AVAudioPlayer *TauntXx;
    AVAudioPlayer *TauntY;
    AVAudioPlayer *TauntYy;
    AVAudioPlayer *TauntZ;
    AVAudioPlayer *TauntZz;
    AVAudioPlayer *TauntAA;
    AVAudioPlayer *TauntAaA;
    AVAudioPlayer *TauntBB;
    AVAudioPlayer *TauntBbB;
    AVAudioPlayer *TauntCC;
    AVAudioPlayer *TauntCcC;
    AVAudioPlayer *TauntDD;
    AVAudioPlayer *TauntDdD;
    AVAudioPlayer *reggySmash;
    AVAudioPlayer *rockPull;
    AVAudioPlayer *reggyLightning;
    SKTexture *keyTexture;
    SKSpriteNode *key;
    SKTexture *money1Texture;
    SKSpriteNode *money1;
    SKTexture *money2Texture;
    SKSpriteNode *money2;
    SKTexture *congradsBoardTexture;
    SKSpriteNode *congradsBoard;
    SKTexture *congradsBoardAnimsTexture;
    SKSpriteNode *congradsBoardAnims;
    SKTexture *lvlNumberTexture;
    SKSpriteNode *lvlNumber;
    SKTexture *cloudsTexture;
    SKSpriteNode *clouds;
    SKTexture *filterTexture;
    SKSpriteNode *filter;
    AVAudioPlayer *confettiSound;
    SKTexture *explosionTexture;
    SKSpriteNode *explosion;
    SKTexture *energyPullTexture;
    SKSpriteNode *energyPull;
    SKTexture *foodWaterfallTexture;
    SKSpriteNode *foodWaterfall;
    
    SKTexture *unlockableLock1Texture;
    SKSpriteNode *unlockableLock1;
    SKTexture *unlockableLock2Texture;
    SKSpriteNode *unlockableLock2;
    SKTexture *unlockableLock3Texture;
    SKSpriteNode *unlockableLock3;
    SKTexture *threeXDamageTexture;
    SKSpriteNode *threeXDamage;
    SKTexture *threeXDamageLockTextTexture;
    SKSpriteNode *threeXDamageLockText;
    SKTexture *criticalHitTexture;
    SKSpriteNode *criticalHit;
    SKTexture *criticalHitLockTextTexture;
    SKSpriteNode *criticalHitLockText;
    SKTexture *antiFreezeTexture;
    SKSpriteNode *antiFreeze;
    SKTexture *antiFreezeLockTextTexture;
    SKSpriteNode *antiFreezeLockText;
    SKTexture *reggyHealthBarIconTexture;
    SKSpriteNode *reggyHealthBarIcon;
    SKTexture *reggyHealthBarTexture;
    SKSpriteNode *reggyHealthBar;
    SKTexture *reggyEnergyBarTexture;
    SKSpriteNode *reggyEnergyBar;
    
    //SKTexture *objMoney1Texture;
    //SKSpriteNode *objMoney1;
    //SKTexture *objMoney2Texture;
    //SKSpriteNode *objMoney2;
    SKTexture *congradsOkTexture;
    SKSpriteNode *congradsOk;
    
    SKAction *yourSoundAction;
    
    //SKAction *wonAmount;
    SKTexture *beginBattleTexture;
    SKSpriteNode *beginBattle;
    SKTexture *frozenScreenTexture;
    SKSpriteNode *frozenScreen;
    SKTexture *eatRadiusTexture;
    SKSpriteNode *eatRadius;
    
    SKAction *sequenceFBG;
    
    //SKAction *HG10Ani;
    //SKAction *HG20Ani;
    //SKAction *HG30Ani;
    
    SKTexture *prizeShineTexture;
    SKSpriteNode *prizeShine;
    NSArray *LGPSAni;
    SKTexture *pMBackButtonTexture;
    SKSpriteNode *pMBackButton;
    SKTexture *foodButtonTexture;
    SKSpriteNode *foodButton;
    SKTexture *objectiveButtonTexture;
    SKSpriteNode *objectiveButton;
    SKTexture *objectivesTexture;
    SKSpriteNode *objectives;
    SKTexture *levelFoodsTexture;
    SKSpriteNode *levelFoods;
    SKTexture *leaveGamePSTexture;
    SKSpriteNode *leaveGamePS;
    SKTexture *okPSTexture;
    SKSpriteNode *okPS;
    SKTexture *cancelPSTexture;
    SKSpriteNode *cancelPS;
    
    SKTexture *helpButtonTexture;
    SKSpriteNode *helpButton;
    SKTexture *punchTexture;
    SKSpriteNode *punch;
    SKTexture *punchTextTexture;
    SKSpriteNode *punchText;
    SKTexture *batRadiusTexture;
    SKSpriteNode *batRadius;
    SKTexture *wall1Texture;
    SKSpriteNode *wall1;
    SKTexture *wall2Texture;
    SKSpriteNode *wall2;
    SKTexture *wall3Texture;
    SKSpriteNode *wall3;
    SKTexture *wall4Texture;
    SKSpriteNode *wall4;
    
    SKTexture *damageScreenTexture;
    SKSpriteNode *damageScreen;
    SKTexture *damageValueTexture;
    SKSpriteNode *damageValue;
    SKTexture *continueBattleTexture;
    SKSpriteNode *continueBattle;
    SKTexture *retryBattleTexture;
    SKSpriteNode *retryBattle;
    
    SKTexture *lightningShadeTexture;
    SKSpriteNode *lightningShade;
    SKTexture *lightningLightTexture;
    SKSpriteNode *lightningLight;
    SKTexture *lightningSmashTexture;
    SKSpriteNode *lightningSmash;
    
    SKTexture *spareButtonTexture;
    SKSpriteNode *spareButton;
    SKTexture *destroyButtonTexture;
    SKSpriteNode *destroyButton;
    SKLabelNode *lifeBarCount;
    SKLabelNode *reggyBarCount;
    
    NSString *damageStringValue;
    SKLabelNode *punchLabel;
    
    SKTexture *reviveButtonTexture;
    SKSpriteNode *reviveButton;
    
    AVAudioPlayer *taunt;
    AVAudioPlayer *prizeCollected;
    
    SKTexture *creditsTexture;
    SKSpriteNode *credits;
    SKTexture *reggyCrownTexture;
    SKSpriteNode *reggyCrown;
    
    
    SKTextureAtlas *gameSceneSpritesOne;
    SKTextureAtlas *gameSceneSpritesTwo;
    SKTextureAtlas *gameSceneSpritesThree;
    SKTextureAtlas *gameSceneSpritesFour;
    SKTextureAtlas *gameSceneSpritesFive;
    SKTextureAtlas *gameSceneSpritesSix;
    SKTextureAtlas *gameSceneSpritesSeven;
    SKTextureAtlas *gameSceneSpritesEight;
    SKTextureAtlas *gameSceneSpritesNine;
    //SKTextureAtlas *gameSceneSpritesTen;
    SKTextureAtlas *congradSpritesOne;
    SKTextureAtlas *congradSpritesTwo;
    //SKTextureAtlas *congradSpritesThree;
    SKTextureAtlas *congradSpritesFive;
    SKTextureAtlas *congradSpritesFour;
    SKTextureAtlas *congranSpritesFour;
    SKTextureAtlas *congradSpritesSix;
    SKTextureAtlas *congradSpritesSeven;
    SKTextureAtlas *congradSpritesEight;
    SKTextureAtlas *congradSpritesNine;
    SKTextureAtlas *congradSpritesTen;
    SKTextureAtlas *congradSpritesEleven;
    SKTextureAtlas *congradSpritesTwelve;
    SKTextureAtlas *congradSpritesThirteen;
    SKTextureAtlas *congradSpritesFourteen;
    SKTextureAtlas *congradSpritesFifteen;
    //SKTextureAtlas *congradSpritesSixteen;
    //SKTextureAtlas *confettiAnimSprites2;
    //SKTextureAtlas *confettiAnimSprites3;
    //SKTextureAtlas *confettiAnimSprites4;
    SKTextureAtlas *confettiAnimSprites5;
    SKTextureAtlas *confettiAnimSprites6;
    SKTextureAtlas *confettiAnimSprites7;
    SKTextureAtlas *confettiAnimSprites8;
    SKTextureAtlas *confettiAnimSprites9;
    SKTextureAtlas *confettiAnimSprites10;
    SKTextureAtlas *powerUpAnimSprites1;
    SKTextureAtlas *powerUpAnimSprites2;
    SKTextureAtlas *powerUpAnimSprites3;
    SKTextureAtlas *powerUpAnimSprites4;
    SKTextureAtlas *foodSprites;
    SKTextureAtlas *reggyTauntSprites;
    SKTextureAtlas *prizeShineSprites;
    SKTextureAtlas *pauseMenuFoodSprites;
    SKTextureAtlas *pauseMenuObjectiveSprites;
    SKTextureAtlas *reggyAnimSprites;
    SKTextureAtlas *bossBattleIntro1;
    SKTextureAtlas *lightningAttackSprites1;
    SKTextureAtlas *lightningAttackSprites2;
    SKTextureAtlas *lightningAttackSprites3;
    SKTextureAtlas *lightningAttackSprites4;
    SKTextureAtlas *lightningAttackSprites5;
    SKTextureAtlas *ReggyBatPull;
    SKTextureAtlas *ReggyWave;
    SKTextureAtlas *ReggySmashSprites;
    SKTextureAtlas *ReggyFoodFallSprites;
    SKTextureAtlas *ReggyEatSprites;
    SKTextureAtlas *ReggySheildSprites;
    SKTextureAtlas *ReggyMotherBoardSprites;
    SKTextureAtlas *ReggyBigMistake;
    SKTextureAtlas *ReggySpareMe;
    SKTextureAtlas *ReggyWeakHumans;
    SKTextureAtlas *ReggyReggyBoom;
    SKTextureAtlas *EnergyPullSprites;
    SKTextureAtlas *HealthBarSprites;
    SKTextureAtlas *shadeAnimSprites;
    SKTextureAtlas *creditSprites;
}

@property (nonatomic, weak) SKView *skView;
//@property (nonatomic) NormalLogic *logic;
//@property (strong, nonatomic) GameScene *Gscene;
//@property (strong, nonatomic) MainMenu *Mainscene;
//@property (strong, nonatomic) ArcadeMenu *FFArcade;
//@property (strong, nonatomic) FBLabelLogic *FBLLogic;
//@property (strong, nonatomic) RankLogic *rankLogic;
//@property (strong, nonatomic) ShopLogic *shopLogic;
//@property (nonatomic) Food *food;
@property (nonatomic) BOOL isAFruit;
@property (nonatomic) BOOL isAVeggy;
@property (nonatomic) BOOL isAOther;
@property (nonatomic) BOOL isWorth1Point;
@property (nonatomic) BOOL isWorth2Points;
@property (nonatomic) BOOL isWorth3Points;
@property (nonatomic) BOOL isWorth4Points;
@property (nonatomic) BOOL isWorth5Points;
@property (nonatomic) BOOL isWorth6Points;
@property (nonatomic) BOOL isWorth7Points;
@property (nonatomic) BOOL isWorth8Points;
@property (nonatomic) BOOL isWorth9Points;
@property (nonatomic) BOOL isWorth10Points;
@property (nonatomic) BOOL isWorth11Points;
@property (nonatomic) BOOL isWorth12Points;
@property (nonatomic) BOOL isWorth13Points;
@property (nonatomic) BOOL isWorth14Points;
@property (nonatomic) BOOL isWorth15Points;
@property (nonatomic) BOOL isWorth16Points;
@property (nonatomic) BOOL isWorth17Points;
@property (nonatomic) BOOL isWorth18Points;
@property (nonatomic) BOOL isWorth19Points;
@property (nonatomic) BOOL isWorth20Points;
@property (nonatomic) BOOL isWorth21Points;
@property (nonatomic) BOOL isWorth22Points;
@property (nonatomic) BOOL isWorth23Points;
@property (nonatomic) BOOL isWorth24Points;
@property (nonatomic) BOOL isWorth25Points;
@property (nonatomic) BOOL isWorth26Points;
@property (nonatomic) BOOL isWorth27Points;
@property (nonatomic) BOOL isWorth28Points;
@property (nonatomic) BOOL isWorth29Points;
@property (nonatomic) BOOL isWorth30Points;
@property (nonatomic) BOOL isWorth31Points;
@property (nonatomic) BOOL isWorth32Points;
@property (nonatomic) BOOL isWorth33Points;
@property (nonatomic) BOOL isWorth34Points;
@property (nonatomic) BOOL isWorth35Points;
@property (nonatomic) BOOL isWorth36Points;
@property (nonatomic) BOOL isWorth37Points;
@property (nonatomic) BOOL isWorth38Points;
@property (nonatomic) BOOL isWorth39Points;
@property (nonatomic) BOOL isWorth40Points;

@property (nonatomic) BOOL activateDP;
@property (nonatomic) BOOL activateTP;
@property (nonatomic) BOOL activateQP;
@property (nonatomic) BOOL activateEL1;
@property (nonatomic) BOOL activateEL2;
@property (nonatomic) BOOL activateEL3;
@property (nonatomic) BOOL activateHG10;
@property (nonatomic) BOOL activateHG20;
@property (nonatomic) BOOL activateHG30;
@property (nonatomic) BOOL activateHS10;
@property (nonatomic) BOOL activateHS20;
@property (nonatomic) BOOL activateHS30;

@property (nonatomic) BOOL isTier1;
@property (nonatomic) BOOL isTier2;
@property (nonatomic) BOOL isTier3;

@property (nonatomic) BOOL swiped;

@property (nonatomic) BOOL rightWay;

@property (nonatomic) BOOL justWonPrize;

@property (nonatomic) BOOL bronzeDrop;
@property (nonatomic) BOOL silverDrop;
@property (nonatomic) BOOL goldDrop;

@property (nonatomic) BOOL isANectarine;
@property (nonatomic) BOOL isAPumpkin;
@property (nonatomic) BOOL isAEggPlant;
@property (nonatomic) BOOL isASourSop;
@property (nonatomic) BOOL isADiakon;
@property (nonatomic) BOOL isAOca;
@property (nonatomic) BOOL isAMangoSteen;
@property (nonatomic) BOOL isAHornedCucumber;
@property (nonatomic) BOOL isADragonFruit;
@property (nonatomic) BOOL isASunchok;
@property (nonatomic) BOOL isASalsify;

//-(void)addSpritesForFoods:(NSSet *)foods;
-(void)rightSensorLayerSprite;
-(void)leftSensorLayerSprite;
-(void)givePowerUps;

@end
